import os

FINNHUB_API_KEY = os.environ.get("FINNHUB_API_KEY")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
ALPACA_API_KEY = os.environ.get("ALPACA_API_KEY")
ALPACA_SECRET_KEY = os.environ.get("ALPACA_SECRET_KEY")

if not all([FINNHUB_API_KEY, GEMINI_API_KEY, ALPACA_API_KEY, ALPACA_SECRET_KEY]):
    raise RuntimeError("Missing API keys in environment variables.")

# === Bot Settings ===
MAX_POSITION_PCT = 0.08
STOP_LOSS_PCT = -6.0
TAKE_PROFIT_PCT = 15.0
TRADE_COOLDOWN_MINUTES = 30
MAX_NEWS_ITEMS = 12
GEMINI_MODEL = "gemini-1.5-flash"

PRICE_HISTORY_DAYS = 5
RSI_PERIOD = 14
SMA_SHORT = 20
SMA_LONG = 50
VOLUME_LOOKBACK = 20
